# Generated by Django 3.1.5 on 2021-01-18 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EndItem',
            fields=[
                ('end_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('nomenclature', models.CharField(max_length=45)),
                ('part_number', models.CharField(max_length=45)),
                ('serial_number', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='EqAccount',
            fields=[
                ('eq_account_number', models.AutoField(primary_key=True, serialize=False)),
                ('eq_account_custodian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('sub_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_serial_number', models.CharField(max_length=45)),
                ('sub_part_number', models.CharField(max_length=45)),
                ('sub_nomenclature', models.CharField(max_length=45)),
                ('sub_item_end_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.enditem')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes_account_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ims.eqaccount')),
                ('notes_custodian_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('notes_end_item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ims.enditem')),
                ('notes_sub_item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ims.subitem')),
            ],
        ),
        migrations.AddField(
            model_name='enditem',
            name='end_item_account_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.eqaccount'),
        ),
    ]
