# Generated by Django 3.1.5 on 2021-01-23 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enditem',
            name='end_item_account_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.eqaccount'),
        ),
    ]
