# Generated by Django 3.1.5 on 2021-01-28 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_auto_20210123_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enditem',
            name='end_item_account_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.eqaccount'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='sub_item_end_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.enditem'),
        ),
    ]
