# Generated by Django 3.1.5 on 2021-01-30 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ims', '0003_auto_20210128_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqaccount',
            name='eq_account_custodian_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
