# Generated by Django 3.1.5 on 2021-01-30 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ims', '0004_auto_20210129_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqaccount',
            name='eq_account_custodian_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
