# Generated by Django 3.1.5 on 2021-02-03 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_auto_20210129_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subitem',
            old_name='sub_item_end_item_id',
            new_name='sub_item_end_item',
        ),
    ]
