# Generated by Django 3.1.5 on 2021-02-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_auto_20210202_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='enditem',
            name='status',
            field=models.CharField(choices=[('SR', 'Serviceable'), ('R', 'Needs Repair'), ('NR', 'Unrepairable')], default='SR', max_length=45),
        ),
        migrations.AddField(
            model_name='note',
            name='entry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='sub_serial_number',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
